### ISSUE TITLE
Add option to specify relative uri for service

### ISSUE THREAD

**Issue by kgibm** [knative-sandbox/kn-plugin-source-kafka#301]
### Feature request

One useful addition would be a relative `uri` option when specifying a service sink.

### Use case

It's very common for the CloudEvents endpoint to be at a URI other than `/`. `KafkaSource` supports `uri` [in addition to `ref`](https://knative.dev/docs/eventing/sinks/#sink-as-a-parameter):

> uri: [...] Relative URIs are resolved using the base URI retrieved from Ref.

I had to use YAML instead:

```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: mysource
spec:
  bootstrapServers:
  - my-cluster-kafka-bootstrap.amq-streams-kafka.svc:9092
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: myservice
    uri: "/api/cloudevents/mytopic"
  topics:
  - mytopic
```

### UI Example

```
kn source kafka create mysource --servers my-cluster-kafka-bootstrap.amq-streams-kafka.svc:9092 --topics mytopic --sink myservice --uri /api/cloudevents/mytopic
```
